# Generated by Django 5.0.7 on 2024-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
