# Generated by Django 5.0.7 on 2024-08-07 20:45

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_alter_authuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2024, 8, 7, 20, 45, 12, 364955, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='surname',
            field=models.CharField(default=datetime.datetime(2024, 8, 7, 20, 45, 21, 756862, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=90, unique=True),
        ),
    ]
