# Generated by Django 5.0.7 on 2024-08-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0003_authuser_firstname_authuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=56, unique=True),
        ),
    ]
