# Generated by Django 5.0.7 on 2024-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0006_authuser_is_verified_authuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=56),
        ),
    ]
