# Generated by Django 5.0.7 on 2024-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0007_alter_authuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
