# Generated by Django 5.0.7 on 2024-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('government_id', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='recovery_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
