# Generated by Django 5.0.7 on 2024-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0010_accountrecoveryrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='government_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='government_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='government_ids/'),
        ),
    ]
